name: test

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test
